### ISSUE TITLE
Scores

### ISSUE THREAD

**Issue by Hdwilburn** [thomaswilburn/shelf-test#1]

**Comment by Hdwilburn** [comment]
Is it possible to add a running score to the test? Maybe 3 points for correct and subtract 1 for incorrect? First day went well!

**Comment by thomaswilburn** [comment]
Sure, should be easy to do. I'll tackle that this weekend, probably adding name and score to a status line that's always in the upper-right.

**Comment by thomaswilburn** [comment]
Name and score added as of commit 92a36eefdd53bc2b71d559d6142549a3bc18a5ed
